### ISSUE TITLE
Right-aligned header overlaps with sign

### ISSUE THREAD

**Issue by everhardt** [drvic10k/bootstrap-sortable#84]
I'd like to align the content of columns containing numbers to the right, as it's easier to read if you format the numbers with the same number of decimals. I do this by adding "text-align: right" to the <td>'s and  the <th>.

And that's where it goes wrong: the header then overlaps with the sorting sign. CSS is not my specialty, is this easily fixable?

**Comment by drvic10k** [comment]
sorry, I somehow missed this issue.
you can do it easily, just change in the style for `sign` class `right: 5px;` to `left: 5px`
if you are using other then the arrow sign, edit the style for `table.sortable th:after` in the same way

**Comment by everhardt** [comment]
Thanks for your help! Would it also be possible to still have the sign at
the right hand side, and the header text a little bit to the left of that,
right aligned?

**Comment by cmfcmf** [comment]
If you are like me and use Bootstrap's `text-right` class, the following bit of CSS might help you to automatically move the arrow to the left side:
```css
table.sortable th.text-right:after {
    left: 5px !important;
}
table.sortable th.text-right span.sign {
    left: 5px !important;
}
```
